### ISSUE TITLE
BP5758D + BK7231N Bugs

### ISSUE THREAD

**Issue by jmacato** [openshwprojects/OpenBK7231T_App#175]
So i have a generic Tuya RGBCW lamp with the chips abovementioned, the hacking/flashing part worked brilliantly but i encountered three problems:

1) Setting the channel mapping on the initial configuration website doesnt seem to work (The values gets set to 40 0 40 0 etc, i suspect that there could be some url encoding issues?)

2) Setting colors with BP5758D_RGBCW is staggerred in the channels (blue turns on then red with around 200ms delay per each channel, etc.. instead of just instantly changing.

3) Setting colors to black/toggling off the lamp sometimes makes the lamp go slightly dim then goes brighter gradually after a minute, plateauing into a very unpleasant brightness.

**Comment by openshwprojects** [comment]
I will try to look into it, but latest release (as of yesterday) runs fine on my BK7231N:
![image](https://user-images.githubusercontent.com/85486843/186837741-c36afb8e-b06e-48bd-bf6f-da0346725033.png)

Do you have a UART flash circuit still connected?

**Comment by jmacato** [comment]
@openshwprojects hmm i was not able to do a direct uart flashing of the devices, only OTA via tuya-cloudcutter.. Should i try to update to the newest firmware?

**Comment by jmacato** [comment]
<img width="443" alt="Screen Shot 2022-08-26 at 3 49 41 PM" src="https://user-images.githubusercontent.com/16554748/186851209-7e8b5569-3a13-426f-8d0b-8b4a74d6f9ec.png">

This is the current

**Comment by jmacato** [comment]
tested on latest firmware, still the same 3 issues

**Comment by openshwprojects** [comment]
can you show any more screenshots of the issues?

**Comment by jmacato** [comment]
Issue 1 : 
![Screenshot from 2022-08-26 22-18-17](https://user-images.githubusercontent.com/16554748/186924829-314c62d8-1576-4681-9905-60fe52ccc742.png)

Issue 2:
https://user-images.githubusercontent.com/16554748/186924930-9651c4f2-ecbf-4eb3-a020-67a78bb3c91d.MOV

Issue 3:
https://user-images.githubusercontent.com/16554748/186925187-e48a69bc-c9b8-48ca-8f1a-9e8f59e84c75.MOV

**Comment by jmacato** [comment]
@openshwprojects do tell if you need more info to help on resolving these bugs

**Comment by openshwprojects** [comment]
"out of range" stuff fixed in:
https://github.com/openshwprojects/OpenBK7231T_App/commit/6d3dac179efda72ad57bf0885a1fa687b3fad418
that was a silly mistake, how could I not spot that earlier.

Can you recheck if it solves all of your problems, or is there still some problem?

**Comment by jmacato** [comment]
@openshwprojects confirmed fix for that Map command issue! Issues 2/3 still persists however

**Comment by jmacato** [comment]
Also another bug: missing HA MQTT quick config

**Comment by openshwprojects** [comment]
@jmacato  the quick config is simply not implemented

regarding other stuff, wait, I might be able to get a similar bulb today, let's hope its BP5758 based

**Comment by jmacato** [comment]
@openshwprojects awesome, looking forward to your findings!

**Comment by openshwprojects** [comment]
@jmacato oh no, it works!
![20220909_142017443_iOS](https://user-images.githubusercontent.com/85486843/189385380-762d8e9e-9e17-45a7-bfc2-4fc0e8f1e443.jpg)
![20220909_142020813_iOS](https://user-images.githubusercontent.com/85486843/189385388-83d0c27c-0fb8-4667-b892-06261f7f14b4.jpg)
![20220909_142235813_iOS](https://user-images.githubusercontent.com/85486843/189385392-15104abe-dd14-4b3c-be74-5c5c48cc41a0.jpg)
![20220909_142555034_iOS](https://user-images.githubusercontent.com/85486843/189385396-9d92dfb8-9c10-41c0-8468-5b17264ef35c.jpg)
![image](https://user-images.githubusercontent.com/85486843/189385519-830b80e1-ec4d-4757-819d-38777bc99515.png)
![image](https://user-images.githubusercontent.com/85486843/189385730-66c4fae0-996c-4b57-9bf4-2429e062ad40.png)
I have no MQTT connected yet, still testing, and Blue and Red are swapped (need to remap colors) but no staggering

and toggle from panel test:
![image](https://user-images.githubusercontent.com/85486843/189396763-2d8d0908-0cc9-4d15-a1a2-447fa309006a.png)
https://imgur.com/a/GdIvQOY

so the question now is why your case is different...
have you tried with MQTT disabled?

**Comment by jmacato** [comment]
I havent tried with mqtt disabled yet. How should i do it?

**Comment by jmacato** [comment]
idk if this has any bearing on the issues but this is my pin cfg ![IMG_20220910_003247.jpg](https://user-images.githubusercontent.com/16554748/189398297-2607a3b0-c5e0-4758-89ab-e8f6a77c2878.jpg)

**Comment by openshwprojects** [comment]
@jmacato enter empty credintials to MQTT (empty strings)

**Comment by jmacato** [comment]
yeah ive tried that to no avail :'(

**Comment by openshwprojects** [comment]
@jmacato do you have anything else running? TCP command line? DGR?

**Comment by jmacato** [comment]
@openshwprojects no nothing else, im sure this is all stock except for the pin settings and the override for the toggles and stuff

**Comment by openshwprojects** [comment]
how do you know which pin is CLK and which is DATA?

**Comment by jmacato** [comment]
i had to sacrifice a spare bulb then cross referenced the bekken ic pinouts, i checked which pins were used and it was pins 24 and 26.. i just swapped both until i found out the correct sequence

**Comment by jmacato** [comment]
![image](https://user-images.githubusercontent.com/16554748/189409525-3db51ca2-8121-4683-8edc-0599ac1ffb46.jpeg)![image](https://user-images.githubusercontent.com/16554748/189409570-dedf5cf1-0395-4094-9049-af7310e38ec3.jpeg)![image](https://user-images.githubusercontent.com/16554748/189409684-f929f33b-e2a1-4e25-83dc-e3e67881cc62.jpeg)

**Comment by openshwprojects** [comment]
BL2028N ?

**Comment by jmacato** [comment]
@openshwprojects yeah, could be a nee version of bk7231n?

**Comment by jmacato** [comment]
@openshwprojects anyway the firmware flashed fine with that board so yeah. maybe theres some differences? not sure

**Comment by openshwprojects** [comment]
I have never heard about this chip variation before.
Where did you buy your lamp? How the packaging looks like?

**Comment by jmacato** [comment]
@openshwprojects here is where i bought it:
https://www.lazada.com.ph/products/i2733993362-s13095148843.html?urlFlag=true&mp=1&spm=spm%3Da2o4l.order_details.item_title.1
![F179B722-4154-458B-B9C6-83444EF95121_1_105_c](https://user-images.githubusercontent.com/16554748/189517120-b7aaed79-e1bb-4493-9a62-0844e148917c.jpeg)
![B5A564C4-6543-4A05-9F71-8EFF180D95DD_1_105_c](https://user-images.githubusercontent.com/16554748/189517122-cf9aba7f-c0b4-464f-8819-fa2920b257c9.jpeg)
![657B28E8-C14B-4332-9490-EEF71FD96767_1_105_c](https://user-images.githubusercontent.com/16554748/189517124-1e1da360-10c1-45a0-86cb-4500e11203cd.jpeg)
![CD73F59C-4D92-4971-B583-C24115ACEC31_1_105_c](https://user-images.githubusercontent.com/16554748/189517127-b2d78f0b-e34b-48d1-8457-2be6991707b1.jpeg)

**Comment by openshwprojects** [comment]
I just had another BP5758D bulb with BK7231N and it works OK again.
I need to get your model of chip and bulb. Have you seen that one on eBay or Aliexpress?

**Comment by jmacato** [comment]
@openshwprojects perhaps i can ship a unit to you? i cant find this exact model on aliexpress/ebay at all

**Comment by DSchndr** [comment]
@jmacato can you test if it behaves the same with the fw from #221?

**Comment by jmacato** [comment]
@DSchndr  perfect!!! This fixes the creeping turning on issue no. 3!!

**Comment by openshwprojects** [comment]
Great job @DSchndr , I don't know exactly what this issue haven't happened for the first person who tested BP5758D but at least it's resolved now.

Any ideas on the remaining problems?

@jmacato  you could ship to me, but what would be a cost of doing that to Poland?  Prices can be crazy these days.

**Comment by openshwprojects** [comment]
@jmacato  I have an idea, what about this?
https://github.com/openshwprojects/OpenBK7231T_App/commit/9f78072141578ae07d318ca40cbab9b369c18648

**Comment by jmacato** [comment]
@openshwprojects It's Fixed!!!! :D I think i can close this now since https://github.com/openshwprojects/OpenBK7231T_App/commit/9f78072141578ae07d318ca40cbab9b369c18648 is merged?

**Comment by DSchndr** [comment]
@openshwprojects In terms of timing we could do some tuning (I have no lamp with this driver tho)
![image](https://user-images.githubusercontent.com/19175445/193750037-a3ce87a2-79c6-4cc2-9638-3dc743c90602.png)

As for the staggering issue... does it happen on turn on? If so we could add the workaround of setting the colors first then output enable

**Comment by openshwprojects** [comment]
@jmacato thank you for testing, if you have some free time, please post the device information (photos + where to buy if possible + case photos + internal photos), obk config screenshots, and maybe a photo in action in our Teardowns forum, here: https://www.elektroda.com/rtvforum/forum507.html , as we are making a large database of IOT information for users. You can also consider posting your config here: https://github.com/OpenBekenIOT/webapp/blob/gh-pages/devices.json

@DSchndr it seems that the DELAY value for this chip can indeed be made slightly lower, but since it already works, I'm not sure it's worth the effort

**Comment by jmacato** [comment]
@DSchndr i think the staggering issue was caused by the large delays when the firmware was using rtos sleep instead of just usleep, now that issue is gone :D 

@openshwprojects will do! hopefully i can do it asap
