### ISSUE TITLE
Setting flag smooth transitions for LED makes MQTT unusable

### ISSUE THREAD

**Issue by Cybermb** [openshwprojects/OpenBK7231T_App#485]
**Describe the bug**
I have recently modified nedis smartlife RGBCW led strip controller with this firmware. With some configuration and lots of doc reading everything works fine. I have integrated controller with home assistant using MQTT. I love the feature flag to smooth color transition, except it only works when changing colors in controllers webui. It does not work with MQTT commands or trough webapp status page. Instead, it changes the color for a fraction of the second and then returns to the value set in controllers webui

**Firmware:**
- Version [e.g. 1.15.55]
- Chip/model: BK7231N

**To Reproduce**
1. Go to "configure general"
2. Set flag [LED] Smooth transitions for LED (EXPERIMENTAL)
3. Send MQTT command or in webapp > status > change values
4. Led strip blinks for a fraction of second and returns to the value set by controller.

**Comment by openshwprojects** [comment]
I think it may  have been just fixed tomorrow or today with the MQTT update, but take care with flashing, it's an initial version of a more stable MQTT approach.

**Comment by Cybermb** [comment]
@openshwprojects do you mean version 1.15.70? I have flashed it but issue still remains

**Comment by GravityRZ** [comment]
was there not an issue with timing with the sm2135 loosing network connection when combined with the smooth transitions option. i thought they fixed that but this looks related

**Comment by Cybermb** [comment]
Is it planned to be fixed? @openshwprojects
